#!/usr/bin/env python3
"""Move a media_stack.py installation to the selfhost program.

Place this file and the selfhost program in the folder that holds the
Python installation's .env, then run this file. It moves the Python files
into python-backup/ and runs 'selfhost setup', which reuses every saved value
and finished step and installs automatic start for selfhost.
"""

import os
import shutil
import subprocess
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent
BACKUP = ROOT / "python-backup"
PROGRAM = ROOT / ("selfhost.exe" if os.name == "nt" else "selfhost")
PYTHON_FILES = (
    "media_stack.py",
    "vpn_country.py",
    "compose.yaml",
    "homepage",
    "recyclarr",
    "tests",
    "__pycache__",
    ".pytest_cache",
)


class MigrationError(Exception):
    pass


def generated_by_selfhost(path: Path) -> bool:
    with path.open(encoding="utf-8", errors="replace") as handle:
        return handle.readline().startswith("# Generated by selfhost")


def python_files() -> list[Path]:
    found = []
    for name in PYTHON_FILES:
        path = ROOT / name
        if not path.exists():
            continue
        if name == "compose.yaml" and generated_by_selfhost(path):
            continue
        found.append(path)
    return found


def check_folder() -> None:
    if not (ROOT / ".env").is_file():
        raise MigrationError(
            "This folder has no saved Python installation. "
            "Place this file in the folder that holds media_stack.py and its .env file."
        )
    if not PROGRAM.is_file():
        raise MigrationError(
            f"{PROGRAM.name} is missing from this folder. Download it from:\n"
            "https://github.com/inayayousfi/legal-stuff/releases/latest\n"
            f"Save it in this folder as {PROGRAM.name}, then run this file again."
        )
    if os.name != "nt" and not os.access(PROGRAM, os.X_OK):
        raise MigrationError(
            f"{PROGRAM.name} cannot run yet. Allow it with this command, then run this file again:\n"
            f"chmod +x {PROGRAM}"
        )


def move_python_files(paths: list[Path]) -> None:
    taken = [path.name for path in paths if (BACKUP / path.name).exists()]
    if taken:
        raise MigrationError(
            f"{BACKUP} already holds {', '.join(taken)}. "
            "Move those out of it, then run this file again."
        )
    BACKUP.mkdir(exist_ok=True)
    moved: list[Path] = []
    try:
        for path in paths:
            shutil.move(str(path), str(BACKUP / path.name))
            moved.append(path)
    except OSError as error:
        failed = path
        stranded = []
        for path in reversed(moved):
            try:
                shutil.move(str(BACKUP / path.name), str(path))
            except OSError:
                stranded.append(path.name)
        if stranded:
            raise MigrationError(
                f"Cannot move {failed.name}: {error}. "
                f"These files remain in {BACKUP} and must be moved back by hand: {', '.join(stranded)}"
            ) from error
        raise MigrationError(f"Cannot move {failed.name}: {error}. Nothing was moved.") from error
    print(f"Moved {', '.join(path.name for path in paths)} to:")
    print(BACKUP)


def main() -> int:
    try:
        check_folder()
        paths = python_files()
        if paths:
            move_python_files(paths)
    except MigrationError as error:
        print(f"Error: {error}", file=sys.stderr)
        return 1
    print(f"Running {PROGRAM.name} setup. It reuses the saved values and finished steps.", flush=True)
    try:
        return subprocess.run([str(PROGRAM), "setup"], cwd=ROOT).returncode
    except KeyboardInterrupt:
        return 130


if __name__ == "__main__":
    sys.exit(main())
