package caddy

import (
	"fmt"
	"strings"

	"github.com/inayayousfi/legal-stuff/internal/app"
	"github.com/inayayousfi/legal-stuff/internal/apps/tinyauth"
	"github.com/inayayousfi/legal-stuff/internal/settings"
)

// Caddyfile serves every route at the access address. Routes that are not
// public or the fallback pass through the admin sign-in first.
func Caddyfile(v *settings.Values, routes []app.Route) string {
	mode := v.Get(modeKey)
	host := v.Get(hostKey)
	url := v.Get("ACCESS_URL")
	tls := ""
	if mode == Tailscale {
		tls = "\ttls /certs/cert.pem /certs/key.pem\n"
	}
	site := host
	if mode == Local {
		site = "http://" + host
	}

	guard := fmt.Sprintf("\t\tforward_auth %s {\n\t\t\turi /api/auth/caddy\n\t\t}\n", tinyauth.Address)
	var public, protected []string
	var fallback string
	var portSites, internal []string
	for _, route := range routes {
		name := strings.TrimPrefix(route.Path, "/")
		switch {
		case route.Port != 0:
			if route.Path != "" {
				public = append(public, fmt.Sprintf("\t@%s path %s %s/*\n\tredir @%s %s:%d/\n", name, route.Path, route.Path, name, url, route.Port))
			}
			portSites = append(portSites, fmt.Sprintf("%s:%d {\n%s\treverse_proxy %s\n}\n", site, route.Port, tls, route.Upstream))
		case route.Fallback:
			fallback = fmt.Sprintf("\thandle {\n\t\treverse_proxy %s\n\t}\n", route.Upstream)
		case route.Public:
			public = append(public, matchedHandle(name, route, ""))
		default:
			protected = append(protected, matchedHandle(name, route, guard))
		}
		if route.Internal != nil {
			internal = append(internal, fmt.Sprintf(`
# Internal address %s:%d adds the %s path only when it is missing.
http://:%d {
	@missing not path %s %s/*
	rewrite @missing %s{uri}
	reverse_proxy %s
}
`, route.Internal.Name, route.Internal.Port, route.Path, route.Internal.Port, route.Path, route.Path, route.Path, route.Upstream))
		}
	}

	var out strings.Builder
	out.WriteString("# Generated by selfhost from .env. Changes here are overwritten.\n\n")
	fmt.Fprintf(&out, "%s {\n%s", site, tls)
	for _, block := range public {
		out.WriteString(block + "\n")
	}
	for _, block := range protected {
		out.WriteString(block + "\n")
	}
	out.WriteString(fallback)
	out.WriteString("}\n")
	for _, block := range portSites {
		out.WriteString("\n" + block)
	}
	for _, block := range internal {
		out.WriteString(block)
	}
	return out.String()
}

// matchedHandle forwards one path, keeping or removing the path prefix, after
// the guard directives, if any.
func matchedHandle(name string, route app.Route, guard string) string {
	if route.StripPrefix {
		return fmt.Sprintf("\tredir %[1]s %[1]s/\n\thandle_path %[1]s/* {\n%[3]s\t\treverse_proxy %[2]s\n\t}\n", route.Path, route.Upstream, guard)
	}
	return fmt.Sprintf("\t@%[1]s path %[2]s %[2]s/*\n\thandle @%[1]s {\n%[4]s\t\treverse_proxy %[3]s\n\t}\n", name, route.Path, route.Upstream, guard)
}
