package caddy

import (
	"fmt"
	"strings"

	"github.com/inayayousfi/legal-stuff/internal/app"
	"github.com/inayayousfi/legal-stuff/internal/apps/tinyauth"
	"github.com/inayayousfi/legal-stuff/internal/settings"
)

// Caddyfile serves every route at the access address. Routes that are not
// public pass through the admin sign-in first.
func Caddyfile(v *settings.Values, routes []app.Route) string {
	mode := v.Get(modeKey)
	host := v.Get(hostKey)
	url := v.Get("ACCESS_URL")
	tls := ""
	if mode == Tailscale {
		tls = "\ttls /certs/cert.pem /certs/key.pem\n"
	}
	site := host
	if mode == Local {
		site = "http://" + host
	}

	var public, protected []string
	var fallback string
	var portSites, internal []string
	for _, route := range routes {
		name := strings.TrimPrefix(route.Path, "/")
		switch {
		case route.Port != 0:
			if route.Path != "" {
				public = append(public, fmt.Sprintf("\t@%s path %s %s/*\n\tredir @%s %s:%d/\n", name, route.Path, route.Path, name, url, route.Port))
			}
			portSites = append(portSites, fmt.Sprintf("%s:%d {\n%s\treverse_proxy %s\n}\n", site, route.Port, tls, route.Upstream))
		case route.Fallback:
			fallback = fmt.Sprintf("\t\thandle {\n\t\t\treverse_proxy %s\n\t\t}\n", route.Upstream)
		case route.Public:
			public = append(public, matchedHandle("\t", name, route))
		default:
			protected = append(protected, matchedHandle("\t\t", name, route))
		}
		if route.Internal != nil {
			internal = append(internal, fmt.Sprintf(`
# Internal address %s:%d adds the %s path only when it is missing.
http://:%d {
	@missing not path %s %s/*
	rewrite @missing %s{uri}
	reverse_proxy %s
}
`, route.Internal.Name, route.Internal.Port, route.Path, route.Internal.Port, route.Path, route.Path, route.Path, route.Upstream))
		}
	}

	var out strings.Builder
	out.WriteString("# Generated by selfhost from .env. Changes here are overwritten.\n\n")
	fmt.Fprintf(&out, "%s {\n%s", site, tls)
	for _, block := range public {
		out.WriteString(block + "\n")
	}
	fmt.Fprintf(&out, "\thandle {\n\t\tforward_auth %s {\n\t\t\turi /api/auth/caddy\n\t\t}\n\n", tinyauth.Address)
	for _, block := range protected {
		out.WriteString(block + "\n")
	}
	out.WriteString(fallback)
	out.WriteString("\t}\n}\n")
	for _, block := range portSites {
		out.WriteString("\n" + block)
	}
	for _, block := range internal {
		out.WriteString(block)
	}
	return out.String()
}

// matchedHandle forwards one path, keeping or removing the path prefix.
func matchedHandle(indent, name string, route app.Route) string {
	if route.StripPrefix {
		return fmt.Sprintf("%[1]sredir %[2]s %[2]s/\n%[1]shandle_path %[2]s/* {\n%[1]s\treverse_proxy %[3]s\n%[1]s}\n", indent, route.Path, route.Upstream)
	}
	return fmt.Sprintf("%[1]s@%[2]s path %[3]s %[3]s/*\n%[1]shandle @%[2]s {\n%[1]s\treverse_proxy %[4]s\n%[1]s}\n", indent, name, route.Path, route.Upstream)
}
