---
- Media:
    - Jellyfin:
        icon: jellyfin.png
        server: media-stack
        container: jellyfin
        href: http://{{HOMEPAGE_VAR_HOST}}:8096
        description: Watch movies and series
    - Seerr:
        icon: seerr.png
        server: media-stack
        container: seerr
        href: http://{{HOMEPAGE_VAR_HOST}}:5055
        description: Request movies and series
- Admin:
    - qBittorrent:
        icon: qbittorrent.png
        server: media-stack
        container: qbittorrent
        href: http://{{HOMEPAGE_VAR_HOST}}:8080
        description: Manage downloads
    - Sonarr:
        icon: sonarr.png
        server: media-stack
        container: sonarr
        href: http://{{HOMEPAGE_VAR_HOST}}:8989
        description: Manage series
    - Radarr:
        icon: radarr.png
        server: media-stack
        container: radarr
        href: http://{{HOMEPAGE_VAR_HOST}}:7878
        description: Manage movies
    - Prowlarr:
        icon: prowlarr.png
        server: media-stack
        container: prowlarr
        href: http://{{HOMEPAGE_VAR_HOST}}:9696
        description: Manage indexers
