---
- Media:
    - Jellyfin:
        icon: jellyfin.png
        server: media-stack
        container: jellyfin-app
        href: "{{HOMEPAGE_VAR_URL}}/jellyfin"
        description: Watch movies and series
    - Seerr:
        icon: seerr.png
        server: media-stack
        container: seerr
        href: "{{HOMEPAGE_VAR_URL}}/seerr"
        description: Request movies and series
- Admin:
    - qBittorrent:
        icon: qbittorrent.png
        server: media-stack
        container: qbittorrent
        href: "{{HOMEPAGE_VAR_URL}}/qbittorrent/"
        description: Manage downloads
    - Sonarr:
        icon: sonarr.png
        server: media-stack
        container: sonarr-app
        href: "{{HOMEPAGE_VAR_URL}}/sonarr"
        description: Manage series
    - Radarr:
        icon: radarr.png
        server: media-stack
        container: radarr-app
        href: "{{HOMEPAGE_VAR_URL}}/radarr"
        description: Manage movies
    - Prowlarr:
        icon: prowlarr.png
        server: media-stack
        container: prowlarr
        href: "{{HOMEPAGE_VAR_URL}}/prowlarr"
        description: Manage indexers
