services:
  jellyfin-app:
    image: jellyfin/jellyfin:10@sha256:aefb67e6a7ff1debdd154a78a7bbb780fd0c873d8639210a7f6a2016ad2b35db
    container_name: selfnook-jellyfin-app
    user: "${PUID}:${PGID}"
    restart: unless-stopped
    environment:
      JELLYFIN_PublishedServerUrl: "${ACCESS_URL}/jellyfin"
      HEALTHCHECK_URL: http://localhost:8096/jellyfin/health
    ports:
      - "7359:7359/udp"
    volumes:
      - "${CONFIG_DIR}/jellyfin:/config"
      - "${CONFIG_DIR}/jellyfin-cache:/cache"
      - "${MEDIA_DIR}:/media:ro"
