services:
  qbittorrent:
    image: qbittorrentofficial/qbittorrent-nox:latest@sha256:9ebb534fe30bab98622cb84a8c3acecfd88319b2d540f52ecdec7b9f866374d7
    container_name: qbittorrent
    restart: unless-stopped
    stop_grace_period: 30m
    environment:
      PUID: "${PUID}"
      PGID: "${PGID}"
      TZ: "${TZ}"
      QBT_LEGAL_NOTICE: "${QBT_LEGAL_NOTICE}"
      QBT_WEBUI_PORT: "8080"
      QBT_TORRENTING_PORT: "6881"
    network_mode: "service:${VPN_GATEWAY_SERVICE}"
    volumes:
      - "${CONFIG_DIR}/qbittorrent:/config"
      - "${MEDIA_DIR}:/media"
