package stack

import (
	"bytes"
	"fmt"
	"io/fs"
	"path/filepath"
	"strings"
	"text/template"

	"github.com/inayayousfi/selfnook/internal/app"
	"github.com/inayayousfi/selfnook/internal/files"
	"github.com/inayayousfi/selfnook/internal/settings"
)

// composeDir holds each app's fragment and build files, written from the program.
const composeDir = "compose"

// writeCompose writes every app's Compose files under compose/<app>/ and the
// compose.yaml that includes them, so docker compose runs from Root.
func (s *Stack) writeCompose(values *settings.Values) error {
	routes, _ := s.contributions(values)
	data := app.ComposeData{Routes: routes}
	var main strings.Builder
	main.WriteString("# Generated by " + Command + ". Changes here are overwritten.\n")
	main.WriteString("name: " + app.Name + "\n\ninclude:\n")
	for _, a := range s.Apps {
		if a.Compose == nil {
			continue
		}
		target := filepath.Join(s.Root, composeDir, a.Name)
		if err := writeAppFiles(a.Compose, target, data); err != nil {
			return fmt.Errorf("Cannot write the %s Compose files: %w", a.Name, err)
		}
		fmt.Fprintf(&main, "  - path: %s/%s/compose.yaml\n    project_directory: .\n    env_file: .env\n", composeDir, a.Name)
	}
	fmt.Fprintf(&main, "\nnetworks:\n  default:\n    name: %s\n    ipam:\n      config:\n        - subnet: %s\n", app.Name, app.NetworkSubnet)
	_, err := files.WriteIfChanged(filepath.Join(s.Root, "compose.yaml"), []byte(main.String()))
	return err
}

// writeAppFiles copies source to target, rendering compose.yaml with data.
func writeAppFiles(source fs.FS, target string, data app.ComposeData) error {
	return fs.WalkDir(source, ".", func(name string, entry fs.DirEntry, err error) error {
		if err != nil || entry.IsDir() {
			return err
		}
		content, err := fs.ReadFile(source, name)
		if err != nil {
			return err
		}
		if name == "compose.yaml" {
			tmpl, err := template.New(name).Option("missingkey=error").Parse(string(content))
			if err != nil {
				return err
			}
			var rendered bytes.Buffer
			if err := tmpl.Execute(&rendered, data); err != nil {
				return err
			}
			content = rendered.Bytes()
		}
		_, err = files.WriteIfChanged(filepath.Join(target, filepath.FromSlash(name)), content)
		return err
	})
}
